### ISSUE TITLE
Save all conda packages for a cdat release in a private repo

### ISSUE THREAD

**Issue by danlipsa** [CDAT/conda-recipes#57]
While working on a different project I noticed the following behavior for C++ conda packages.
I think cdat suffers from the same issues. I propose we adderess these issues as outlined.

1. Conda packages with older versions may disappear (or be rebuilt with different dependencies) in public repositories.

To fix this we store all conda packages in a repository in our own private channels. Anaconda has a limit of 3 GB which may be a problem. Packages can be stored on a regular web server though (http)

2. Having a number of packages built and rebuilding just one package a few weeks later may result in dependency mismatch and in a non working environment.

This is because, at build time, conda pulls the most recent dependencies and makes the package depend on those.
At install time, if there is no dependency on the version number, conda installs the latest version which may not work with packages build a few weeks prior.
Adding version dependency does not solve the problem because of issue 1.

To fix this, I always rebuilt all packages when I had to rebuild one, especially if that rebuild happens a few weeks after I rebuild everything.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 @scottwittenburg What do you think?

**Comment by scottwittenburg** [comment]
This seems like a reasonable path to me, and could make sense to ease some of the issues we always see with installing the environment.  But I have a couple questions:

1. How much developer time do see it taking to maintain this approach over time?  And who will be responsible for building and uploading whenever that is needed?

2. Same question for setup and maintenance of the web server for hosting those packages if we exceed the 3GB limit on `anaconda.org`?

**Comment by danlipsa** [comment]
> This seems like a reasonable path to me, and could make sense to ease some of the issues we always see with installing the environment. But I have a couple questions:
> 
> 1. How much developer time do see it taking to maintain this approach over time?  And who will be responsible for building and uploading whenever that is needed?

I don't think this is much harder than just the building we are doing now. So whoever is building the packages now could do the extra step. 

We need a few days at the beginning to port a script I have that pulls packages from a conda env, figure out what binary packages we need rebuilding every time and get rid of most version pinning that we use.

> 2. Same question for setup and maintenance of the web server for hosting those packages if we exceed the 3GB limit on `anaconda.org`?

I don't know of public http server that we could use. I am sure we could find a server here at Kitware without too much trouble, but probably llnl could find one as well.

**Comment by doutriaux1** [comment]
@danlipsa we already have this setup with our `cdat-forge` channel. I also have an upload script to it somewhere. The first use case was the pcmdi-metrics. See: https://github.com/CDAT/conda-recipes/blob/master/push_env_packages.py and https://anaconda.org/cdat-forge

**Comment by danlipsa** [comment]
Then we should only have our private channel in the lists of channels we download packages from isn't it?
See:
https://raw.githubusercontent.com/cdat/cdat/master/conda/cdat-v80_py2.Linux.yaml
