### ISSUE TITLE
Re-upload cdp 1.4.1?

### ISSUE THREAD

**Issue by xylar** [CDAT/conda-recipes#59]
e3sm_diags 1.5.0 requires cdp 1.4.1, and e3sm-unified 1.2.4 (the most recent version) requires e3sm_diags 1.5.0.  Could someone rebuild and re-upload that version of the package?  I realize there's a newer version but that doesn't fix the problem for us.

**Comment by xylar** [comment]
@doutriaux1?

**Comment by zshaheen** [comment]
@xylar I think we're good now: https://anaconda.org/cdat/cdp/files
