### ISSUE TITLE
vtk-cdat with less restricted py3.7?

### ISSUE THREAD

**Issue by xylar** [CDAT/conda-recipes#64]
Currently, `vtk-cdat` on the `cdat/label/v81` channel has a very restrictive specification of the python 3.7 version:
```
$ conda search --info -c cdat/label/v81 "vtk-cdat=8.2.0rc2.8.1"
...
vtk-cdat 8.2.0rc2.8.1 py37h0645e64_0
------------------------------------
file name   : vtk-cdat-8.2.0rc2.8.1-py37h0645e64_0.tar.bz2
name        : vtk-cdat
version     : 8.2.0rc2.8.1
build       : py37h0645e64_0
build number: 0
size        : 41.6 MB
license     : BSD 3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/cdat/label/v81/linux-64/vtk-cdat-8.2.0rc2.8.1-py37h0645e64_0.tar.bz2
md5         : ea1722f914cc0406122ad1786511f89f
timestamp   : 2019-02-21 17:35:15 UTC
dependencies: 
  - ffmpeg >=4.1,<4.2.0a0
  - future
  - numpy
  - python >=3.7.1,<3.7.2.0a0
  - toolchain3
  - x264 >=1!152.20180717,<1!153
```
For python 3.6, the restruciton is merely:
```
  - python >=3.6,<3.7.0a0
```
This tighter restriction on python 3.7 is causing conflicts (e.g. with `sqlite>=3.29.0`) that require later minor versions.  Would it be possible to upload a new build with less restriction?

**Comment by xylar** [comment]
@sterlingbaldwin, this is at least part of the conflicts you've been seeing.

**Comment by xylar** [comment]
@doutriaux1, is this something that you can take care of?  Or could you recommend someone else?

**Comment by doutriaux1** [comment]
@xylar this one is probably for @danlipsa or @scottwittenburg possibly @downiec

**Comment by doutriaux1** [comment]
@danlipsa what are the current limitation on Python for our vtk-cdat?

**Comment by xylar** [comment]
@doutriaux1 and @danlipsa, for reference, the version of `vtk-cdat` on the `cdat/label/v82` channel seems to work with a later minor version of python, but it still has this really strict versioning, which now applies to 3.6 as well:
```
$ conda search --info -c cdat/label/v82 vtk-cdat
Loading channels: done
vtk-cdat 8.2.0.8.2 py27_mesalibhead77ed_0
-----------------------------------------
file name   : vtk-cdat-8.2.0.8.2-py27_mesalibhead77ed_0.tar.bz2
name        : vtk-cdat
version     : 8.2.0.8.2
build       : py27_mesalibhead77ed_0
build number: 0
size        : 39.8 MB
license     : BSD 3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/cdat/label/v82/linux-64/vtk-cdat-8.2.0.8.2-py27_mesalibhead77ed_0.tar.bz2
md5         : 5f964e381cb8d7c4767c650cd5123fd2
timestamp   : 2019-08-27 06:55:03 UTC
dependencies: 
  - ffmpeg >=4.2,<4.3.0a0
  - future
  - libgcc-ng >=7.3.0
  - libstdcxx-ng >=7.3.0
  - mesalib
  - numpy
  - python >=2.7.15,<2.7.16.0a0
  - x264 >=1!152.20180806,<1!153


vtk-cdat 8.2.0.8.2 py27h3df8362_0
---------------------------------
file name   : vtk-cdat-8.2.0.8.2-py27h3df8362_0.tar.bz2
name        : vtk-cdat
version     : 8.2.0.8.2
build       : py27h3df8362_0
build number: 0
size        : 39.9 MB
license     : BSD 3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/cdat/label/v82/linux-64/vtk-cdat-8.2.0.8.2-py27h3df8362_0.tar.bz2
md5         : 225afce7f266d0d1456ee71a539e3bc1
timestamp   : 2019-08-27 06:35:47 UTC
dependencies: 
  - ffmpeg >=4.2,<4.3.0a0
  - future
  - libgcc-ng >=7.3.0
  - libstdcxx-ng >=7.3.0
  - numpy
  - python >=2.7.15,<2.7.16.0a0
  - x264 >=1!152.20180806,<1!153


vtk-cdat 8.2.0.8.2 py36_mesalibhead77ed_0
-----------------------------------------
file name   : vtk-cdat-8.2.0.8.2-py36_mesalibhead77ed_0.tar.bz2
name        : vtk-cdat
version     : 8.2.0.8.2
build       : py36_mesalibhead77ed_0
build number: 0
size        : 39.9 MB
license     : BSD 3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/cdat/label/v82/linux-64/vtk-cdat-8.2.0.8.2-py36_mesalibhead77ed_0.tar.bz2
md5         : 035fa23310bc862e8fc52ed30756b040
timestamp   : 2019-08-27 06:16:27 UTC
dependencies: 
  - ffmpeg >=4.2,<4.3.0a0
  - future
  - libgcc-ng >=7.3.0
  - libstdcxx-ng >=7.3.0
  - mesalib
  - numpy
  - python >=3.6.7,<3.6.8.0a0
  - x264 >=1!152.20180806,<1!153


vtk-cdat 8.2.0.8.2 py36h3df8362_0
---------------------------------
file name   : vtk-cdat-8.2.0.8.2-py36h3df8362_0.tar.bz2
name        : vtk-cdat
version     : 8.2.0.8.2
build       : py36h3df8362_0
build number: 0
size        : 39.9 MB
license     : BSD 3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/cdat/label/v82/linux-64/vtk-cdat-8.2.0.8.2-py36h3df8362_0.tar.bz2
md5         : f7ea724ba440c3d7f8997fe4e73e5573
timestamp   : 2019-08-27 05:56:25 UTC
dependencies: 
  - ffmpeg >=4.2,<4.3.0a0
  - future
  - libgcc-ng >=7.3.0
  - libstdcxx-ng >=7.3.0
  - numpy
  - python >=3.6.7,<3.6.8.0a0
  - x264 >=1!152.20180806,<1!153


vtk-cdat 8.2.0.8.2 py37_mesalibhead77ed_0
-----------------------------------------
file name   : vtk-cdat-8.2.0.8.2-py37_mesalibhead77ed_0.tar.bz2
name        : vtk-cdat
version     : 8.2.0.8.2
build       : py37_mesalibhead77ed_0
build number: 0
size        : 39.9 MB
license     : BSD 3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/cdat/label/v82/linux-64/vtk-cdat-8.2.0.8.2-py37_mesalibhead77ed_0.tar.bz2
md5         : af0030206df3037dbb3f07308ba1a08e
timestamp   : 2019-08-27 05:37:21 UTC
dependencies: 
  - ffmpeg >=4.2,<4.3.0a0
  - future
  - libgcc-ng >=7.3.0
  - libstdcxx-ng >=7.3.0
  - mesalib
  - numpy
  - python >=3.7.3,<3.7.4.0a0
  - x264 >=1!152.20180806,<1!153


vtk-cdat 8.2.0.8.2 py37h3df8362_0
---------------------------------
file name   : vtk-cdat-8.2.0.8.2-py37h3df8362_0.tar.bz2
name        : vtk-cdat
version     : 8.2.0.8.2
build       : py37h3df8362_0
build number: 0
size        : 39.9 MB
license     : BSD 3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/cdat/label/v82/linux-64/vtk-cdat-8.2.0.8.2-py37h3df8362_0.tar.bz2
md5         : ca3fad78d2147d8c7ebda1ac2e2ad549
timestamp   : 2019-08-27 05:16:26 UTC
dependencies: 
  - ffmpeg >=4.2,<4.3.0a0
  - future
  - libgcc-ng >=7.3.0
  - libstdcxx-ng >=7.3.0
  - numpy
  - python >=3.7.3,<3.7.4.0a0
  - x264 >=1!152.20180806,<1!153
```

I think that's almost certainly going to cause constant problems.

**Comment by danlipsa** [comment]
The only restriction is that python cannot be 3.7.0. I think there was a
bug in that version that make it not work well with VTK.

Maybe pin_run_as_build causes this restriction. We should remove it
altogether I think.

Dan

**Comment by xylar** [comment]
This line:
https://github.com/CDAT/conda-recipes/blob/master/vtk-cdat/conda_build_config.yaml#L7

Yes, I would revert that back to `x.x` or remove it entirely.  It's quite problematic.  Could you also release new builds after doing that?  Specifically of `vtk-cdat=8.2.0rc2.8.1` on the `cdat/label/v81` channel?  But probably of others, too.

Also, I noticed that there are 2 versions of `vtk-cdat-8.2.0.8.2` with build number 0 for each OS at https://anaconda.org/cdat/vtk-cdat/files.  Please try to make sure that doesn't happen because there can be bad side effects.

**Comment by xylar** [comment]
@danlipsa and @doutriaux1, thank you both for the prompt response to this issue. It's very much appreciated!

**Comment by doutriaux1** [comment]
@xylar @danlipsa since 8.2 is not out officially i think we can still tweak things on vtk-cdat at this point, especially for this kind of things that do not alter vtk. @danlipsa do you mind try to take care of this for @xylar ? Thx.

**Comment by doutriaux1** [comment]
@muryanto1 @downiec FYI this is what is happening on vtk-cdat 8.2 right now (see above)

**Comment by xylar** [comment]
@doutriaux1, you should always feel free to make new builds of of your packages like I'm asking for without it being equivalent to a version update or a new release.  That's what conda build numbers are for.

**Comment by chengzhuzhang** [comment]
@xylar Thank you for keeping me in the loop. @danlipsa @dooutriaux1 @muryanto1 @downiec having a new build instead of a version update might require much less work for software build on top of `cdat` (i.e. `e3sm_diags`) for testing, bench-marking and debugging)... Thank you all for working on this.

**Comment by danlipsa** [comment]
> The only restriction is that python cannot be 3.7.0. I think there was a bug in that version that make it not work well with VTK. Maybe pin_run_as_build causes this restriction. We should remove it altogether I think. Dan

Actually we cannot remove pin_run_as_build. It ensures binary compatibility between the python we build against and the python we run against. The following thread 

https://mail.python.org/pipermail/python-dev/2017-March/147707.html

discusses:
- if python is binary compatible between micro versions (3.6.1 to 3.6.2). Most people believe it should even if they report problems.
- if python is binary between minor versions (3.6  and 3.7). It is not.

So probably x.x is is fairly safe even if it might cause problems.

The kind of problems you are seeing could be easily handled by:
1. recompile our packages with the latest conda packages (which includes latest python)
2. Save all packages to a private repository.

https://github.com/CDAT/conda-recipes/issues/57#issuecomment-447387292

**Comment by xylar** [comment]
> So probably x.x is is fairly safe even if it might cause problems.

I think that is perfectly safe.  It is such a ubiquitous practice that lots of conda-forge would be broken if it didn't work.

> The kind of problems you are seeing could be easily handled by:
> 1. recompile our packages with the latest conda packages (which includes latest python)
> 2. Save all packages to a private repository.

If I understand what you are suggesting here, this is actually the opposite of helping with the problem I'm working on.  I realize some people are concerned with preserving specific versions of an entire conda environment.  I'm concerned with maintaining a very large number of python packages for an analysis environment (e3sm-unified) that are constantly being updated.  I need a living, breathing, constantly evolving environment that isn't too pinned down.  The stricter the pinning becomes, the more impossible it becomes for me to find a set of compatible packages.  This is why the over-specific pinning of `vtk-cdat` is causing me a particularly big headache.

So if you're willing to relax to `x.x` instead of `x.x.x` and make new builds of both the old (`cdat/label/v81`) and new (`cdat/label/v82`) with the less restricted python, I think that would be the solution to my problem.

By the way, I think you are all kind of aware of this, but the more packages you move to conda-forge, the easier it will be to get help maintaining versions that are compatible with other conda-forge packages and their pinnings.  I realize certain packages like `vtk-cdat` maybe aren't ready for the move but maybe at least keep it in mind.

**Comment by xylar** [comment]
By the way, I'm sorry if I seem grumpy about this.  I don't mean to take it out on any of you but I spent over 3 frustrating hours today tracking down this issue.

**Comment by danlipsa** [comment]
> > 1. recompile our packages with the latest conda packages (which includes latest python)
> > 2. Save all packages to a private repository.
> 
> If I understand what you are suggesting here, this is actually the opposite of helping with the problem I'm working on. I realize some people are concerned with preserving specific versions of an entire conda environment. 

I am only suggesting this for a release. If you depend on a public repository such as conda-forge for a release you will run into problems, as it happened many times for cdat. The packages in conda forge will evolve so people won't download the same software that you tested. At one point it will break.

> I'm concerned with maintaining a very large number of python packages for an analysis environment (e3sm-unified) that are constantly being updated. I need a living, breathing, constantly evolving environment that isn't too pinned down. The stricter the pinning becomes, the more impossible it becomes for me to find a set of compatible packages. 

I agree.

This is why the over-specific pinning of `vtk-cdat` is causing me a particularly big headache.
> 
> So if you're willing to relax to `x.x` instead of `x.x.x` and make new builds of both the old (`cdat/label/v81`) and new (`cdat/label/v82`) with the less restricted python, I think that would be the solution to my problem.

Sounds good. x.x is probably a better pinning for vtk-cdat.

> By the way, I think you are all kind of aware of this, but the more packages you move to conda-forge, the easier it will be to get help maintaining versions that are compatible with other conda-forge packages and their pinnings. I realize certain packages like `vtk-cdat` maybe aren't ready for the move but maybe at least keep it in mind.

conda-forge only builds releases while we needed many times VTK master because of bug fixes to VTK. But I agree, we should look into merging what we have extra to conda-forge. I don't think they do cross-compiling, besides that I think they are pretty similar.
